subscriberBabiesSettings = {
	--change this to your channel
	twitchchannel = "cobaltstreak",
	--will each sub have the same entity every time? (true/false)
	subSeed = false,
	--if true change this number to switch to a different set of sub dependent entities
	subSeedOffset = 666,
	--tyrone is not letting me access the gui offset so you have to adjust this yourself im sorry :S
	subMessagePos = Vector(45, 45),
	--subscriber message color (0 to 1, a = transparency)
	subMessageColor = { r = 0.8, g = 0.4, b = 0.15, a = 0.85 },
	--subscriber message duration in seconds
	subMessageDuration = 5,
	--subscriber message fade out duration in seconds
	subMessageFadeDuration = 1,
	--subscriber name color
	subNameColor = { r = 1, g = 1, b = 1, a = 0.85 },
	--spawns a few test subs on startup
	debug = true,

	subEnemies = {
		{ type = EntityType.ENTITY_BOOMFLY			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_DINGA			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_GAPER			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_GURGLE			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_BONY				, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_FAT_BAT			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_FATTY			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_GLOBIN			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_CLOTTY			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_MONSTRO			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_SQUIRT			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_FLAMINGHOPPER	, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_LEAPER			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_MRMAW			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_MRMAW			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_ONE_TOOTH		, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_PSY_TUMOR		, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_ONE_TOOTH		, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_GRUB				, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_CAMILLO_JR		, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_MOMS_HAND		, variant = 0									, subType = 0							 },
	},

	subFriendlies = {
		{ type = EntityType.ENTITY_BOOMFLY			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_DIP				, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_RAGE_CREEP		, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_HOPPER			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_GAPER			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_GURGLE			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_BONY				, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_FAT_BAT			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_FATTY			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_SLOT				, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_HOST				, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_VIS				, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_MRMAW			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_MAW				, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_CONJOINED_SPITTY	, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_GUTS				, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_CAMILLO_JR		, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_CHARGER			, variant = 0									, subType = 0							 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_HEART			, subType = HeartSubType.HEART_SOUL	 	 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_HEART			, subType = HeartSubType.HEART_ETERNAL	 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_HEART			, subType = HeartSubType.HEART_BLACK	 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_HEART			, subType = HeartSubType.HEART_GOLDEN	 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_COIN			, subType = CoinSubType.COIN_LUCKYPENNY	 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_COIN			, subType = CoinSubType.COIN_DIME		 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_COIN			, subType = CoinSubType.COIN_STICKYNICKEL},
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_COIN			, subType = CoinSubType.NICKEL			 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_KEY			, subType = KeySubType.KEY_GOLDEN		 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_BOMB			, subType = BombSubType.BOMB_GOLDEN		 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_CHEST			, subType = ChestSubType.CHEST_CLOSED	 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_BOMBCHEST		, subType = 0							 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_ETERNALCHEST	, subType = 0							 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_LOCKEDCHEST	, subType = 0							 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_PILL			, subType = 0							 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_LIL_BATTERY	, subType = 0							 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_REDCHEST		, subType = 0							 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_BED			, subType = 0							 },
		{ type = EntityType.ENTITY_PICKUP			, variant = PickupVariant.PICKUP_REDCHEST		, subType = 0							 },
	},

	subGoodItems = {
		CollectibleType.COLLECTIBLE_SAD_ONION,
		CollectibleType.COLLECTIBLE_INNER_EYE,
		CollectibleType.COLLECTIBLE_SPOON_BENDER,
		CollectibleType.COLLECTIBLE_MAXS_HEAD,
		CollectibleType.COLLECTIBLE_MY_REFLECTION,
		CollectibleType.COLLECTIBLE_ONE_UP,
		CollectibleType.COLLECTIBLE_MAGIC_MUSHROOM,
		CollectibleType.COLLECTIBLE_HEART,
		CollectibleType.COLLECTIBLE_RAW_LIVER,
		CollectibleType.COLLECTIBLE_SKELETON_KEY,
		CollectibleType.COLLECTIBLE_TRANSCENDENCE,
		CollectibleType.COLLECTIBLE_LUNCH,
		CollectibleType.COLLECTIBLE_DINNER,
		CollectibleType.COLLECTIBLE_DESSERT,
		CollectibleType.COLLECTIBLE_BREAKFAST,
		CollectibleType.COLLECTIBLE_ROTTEN_MEAT,
		CollectibleType.COLLECTIBLE_WOODEN_SPOON,
		CollectibleType.COLLECTIBLE_BELT,
		CollectibleType.COLLECTIBLE_MOMS_UNDERWEAR,
		CollectibleType.COLLECTIBLE_MOMS_HEELS,
		CollectibleType.COLLECTIBLE_MOMS_LIPSTICK,
		CollectibleType.COLLECTIBLE_WIRE_COAT_HANGER,
		CollectibleType.COLLECTIBLE_BOOK_OF_BELIAL,
		CollectibleType.COLLECTIBLE_NECRONOMICON,
		CollectibleType.COLLECTIBLE_LUCKY_FOOT,
		CollectibleType.COLLECTIBLE_SHOOP_DA_WHOOP,
		CollectibleType.COLLECTIBLE_STEVEN,
		CollectibleType.COLLECTIBLE_MOMS_EYE,
		CollectibleType.COLLECTIBLE_DISTANT_ADMIRATION,
		CollectibleType.COLLECTIBLE_LADDER,
		CollectibleType.COLLECTIBLE_CHOCOLATE_MILK,
		CollectibleType.COLLECTIBLE_TECHNOLOGY,
		CollectibleType.COLLECTIBLE_GROWTH_HORMONES,
		CollectibleType.COLLECTIBLE_QUARTER,
		CollectibleType.COLLECTIBLE_DEAD_CAT,
		CollectibleType.COLLECTIBLE_SUPER_BANDAGE,
		CollectibleType.COLLECTIBLE_HALO,
		CollectibleType.COLLECTIBLE_DEAD_SEA_SCROLLS,
		CollectibleType.COLLECTIBLE_FORGET_ME_NOW,
		CollectibleType.COLLECTIBLE_PAGEANT_BOY,
		CollectibleType.COLLECTIBLE_BUM_FRIEND,
		CollectibleType.COLLECTIBLE_PONY,
		CollectibleType.COLLECTIBLE_NOTCHED_AXE,
		CollectibleType.COLLECTIBLE_TOUGH_LOVE,
		CollectibleType.COLLECTIBLE_MUTANT_SPIDER,
		CollectibleType.COLLECTIBLE_PEEPER,
		CollectibleType.COLLECTIBLE_ANKH,
		CollectibleType.COLLECTIBLE_GHOST_BABY,
		CollectibleType.COLLECTIBLE_HARLEQUIN_BABY,
		CollectibleType.COLLECTIBLE_SQUEEZY,
		CollectibleType.COLLECTIBLE_SQUEEZY,
		CollectibleType.COLLECTIBLE_GNAWED_LEAF,
		CollectibleType.COLLECTIBLE_PIGGY_BANK,
		CollectibleType.COLLECTIBLE_BALL_OF_TAR,
		CollectibleType.COLLECTIBLE_E_COLI,
		CollectibleType.COLLECTIBLE_INFAMY,
		CollectibleType.COLLECTIBLE_BFFS,
		CollectibleType.COLLECTIBLE_SCREW,
		CollectibleType.COLLECTIBLE_SMART_FLY,
		CollectibleType.COLLECTIBLE_JUICY_SACK,
		CollectibleType.COLLECTIBLE_ROBO_BABY_2,
		CollectibleType.COLLECTIBLE_ROTTEN_BABY,
		CollectibleType.COLLECTIBLE_HEADLESS_BABY,
		CollectibleType.COLLECTIBLE_LEECH,
		CollectibleType.COLLECTIBLE_LIL_HAUNT,
		CollectibleType.COLLECTIBLE_SISSY_LONGLEGS,
		CollectibleType.COLLECTIBLE_BUTTER_BEAN,
		CollectibleType.COLLECTIBLE_CANCER,
		CollectibleType.COLLECTIBLE_JUDAS_SHADOW,
		CollectibleType.COLLECTIBLE_MYSTERIOUS_LIQUID,
		CollectibleType.COLLECTIBLE_GEMINI,
		CollectibleType.COLLECTIBLE_MONGO_BABY,
		CollectibleType.COLLECTIBLE_DIPLOPIA,
		CollectibleType.COLLECTIBLE_MEGA_BEAN,
		CollectibleType.COLLECTIBLE_BOMBER_BOY,
		CollectibleType.COLLECTIBLE_CRACK_JACKS,
		CollectibleType.COLLECTIBLE_MOMS_PEARLS,
		CollectibleType.COLLECTIBLE_8_INCH_NAILS,
		CollectibleType.COLLECTIBLE_FATES_REWARD,
		CollectibleType.COLLECTIBLE_LIL_CHEST,
		CollectibleType.COLLECTIBLE_CHARGED_BABY,
		CollectibleType.COLLECTIBLE_MR_DOLLY,
		CollectibleType.COLLECTIBLE_TECH_X,
		CollectibleType.COLLECTIBLE_SPIDER_MOD,
		CollectibleType.COLLECTIBLE_TRACTOR_BEAM,
		CollectibleType.COLLECTIBLE_FARTING_BABY,
		CollectibleType.COLLECTIBLE_GB_BUG
	},

	subBadItems = {
		CollectibleType.COLLECTIBLE_MY_REFLECTION,
		CollectibleType.COLLECTIBLE_DR_FETUS,
		CollectibleType.COLLECTIBLE_NUMBER_ONE,
		CollectibleType.COLLECTIBLE_IPECAC,
		CollectibleType.COLLECTIBLE_TECHNOLOGY_2,
		CollectibleType.COLLECTIBLE_ABEL,
		CollectibleType.COLLECTIBLE_PLACENTA,
		CollectibleType.COLLECTIBLE_ANTI_GRAVITY,
		CollectibleType.COLLECTIBLE_MONSTROS_LUNG,
		CollectibleType.COLLECTIBLE_TINY_PLANET,
		CollectibleType.COLLECTIBLE_EXPERIMENTAL_TREATMENT,
		CollectibleType.COLLECTIBLE_BBF,
		CollectibleType.COLLECTIBLE_BOBS_BRAIN,
		CollectibleType.COLLECTIBLE_ISAACS_HEART,
		CollectibleType.COLLECTIBLE_PUNCHING_BAG,
		CollectibleType.COLLECTIBLE_THUNDER_THIGHS,
		CollectibleType.COLLECTIBLE_STRANGE_ATTRACTOR,
		CollectibleType.COLLECTIBLE_CURSED_EYE,
		CollectibleType.COLLECTIBLE_LUDOVICO_TECHNIQUE,
		CollectibleType.COLLECTIBLE_SOY_MILK,
		CollectibleType.COLLECTIBLE_DEAD_ONION,
		CollectibleType.COLLECTIBLE_BROKEN_WATCH,
		CollectibleType.COLLECTIBLE_NUMBER_TWO,
		CollectibleType.COLLECTIBLE_PUPULA_DUPLEX,
		CollectibleType.COLLECTIBLE_EDENS_BLESSING,
		CollectibleType.COLLECTIBLE_SPEAR_OF_DESTINY,
		CollectibleType.COLLECTIBLE_EXPLOSIVO,
		CollectibleType.COLLECTIBLE_CHAOS,
		CollectibleType.COLLECTIBLE_FRUIT_CAKE,
		CollectibleType.COLLECTIBLE_ARIES,
		CollectibleType.COLLECTIBLE_EPIC_FETUS,
		CollectibleType.COLLECTIBLE_PARASITE,
		CollectibleType.COLLECTIBLE_RUBBER_CEMENT,
		CollectibleType.COLLECTIBLE_CRICKETS_BODY,
		CollectibleType.COLLECTIBLE_EVES_MASCARA,
		CollectibleType.COLLECTIBLE_MISSING_NO
	}
}